language: php

sudo: false

matrix:
  include:
    - php: 7.0
      env: COLLECT_COVERAGE=true  IGNORE_PLATFORMS=false
    - php: 7.1
      env: COLLECT_COVERAGE=true IGNORE_PLATFORMS=false
    - php: 7.2
      env: COLLECT_COVERAGE=false IGNORE_PLATFORMS=true
    - php: nightly
      env: COLLECT_COVERAGE=false IGNORE_PLATFORMS=true
  allow_failures:
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - if [ "$IGNORE_PLATFORMS" == "true" ]; then travis_retry composer update --no-interaction --prefer-source --ignore-platform-reqs; fi
  - if [ "$IGNORE_PLATFORMS" == "false" ]; then travis_retry composer update --no-interaction --prefer-source; fi

script:
  - composer run-script test

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 94c9e725-0e8c-4b1d-a07a-71d85df390b3